### PR TITLE
Add an Images Directory; Insert Six Example Reference Images

### PR DESCRIPTION
**Pull request by Githubbubber**
I am adding an images directory.

This directory can be used for a developer's reference when it comes to: 
- tickets
- pull requests
- screenshots
- documentation
- etc. 
 
All images can be uploaded here and linked to where needed.

Six example files are added as an illustration of what images can be, as well as serve as examples of _how_ to name an image file.

### CODE REVIEW

**Comment by mnyon-grandkru** [comment]
This is meant to be an example of how to add images to a project, is that correct?

**Comment by Githubbubber** [comment]
> This is meant to be an example of how to add images to a project, is that correct?

No, it’s for non-app usage only: References for spikes, documents, designs, mockups, etc.

**Review by chris-watson — APPROVED** [review]
Looks good!

**Comment by Githubbubber** [comment]
@mnyon-grandkru was your question answered? Do you need any further clarification? If not I will merge this work.

**Comment by mnyon-grandkru** [comment]
@Githubbubber  I am satisfied.

**Pull request merged**
